"""Long-term memory (SQLite) read/write functions.

This module owns only the read/write *functions* — the backend-builder
wires the FastAPI persistence layer (which user_key to pass, when to call
these) around this interface. DB file defaults to
`backend/data/memory.db` (see config.memory_db_path), created on first use.

Tables:
- `risk_tolerance(user_key PRIMARY KEY, value, updated_at)`
- `ticker_analysis(ticker PRIMARY KEY, synthesis, stance, updated_at)`
- `allocation_analysis(user_key PRIMARY KEY, output_json, synthesis, updated_at)`
- `auth_tokens(token PRIMARY KEY, user_key, created_at)` — server-issued
  session credentials. A token is an unguessable random string
  (`secrets.token_urlsafe`) generated by `create_session` below and handed
  to the client once; the client sends it back on every subsequent request
  instead of typing/choosing its own `user_key`. Persisted (not just
  in-process) so a backend restart doesn't invalidate every open frontend
  session while `risk_tolerance`/`ticker_analysis` memory for the same
  `user_key` is still on disk.

All writes are upserts (no deletes in Milestone 1), matching the
architecture design's idempotency note for this tool.
"""
from __future__ import annotations

import os
import secrets
import sqlite3
import json
import uuid
from contextlib import closing
from datetime import datetime, timezone

from .config import config

_SCHEMA = """
CREATE TABLE IF NOT EXISTS risk_tolerance (
    user_key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS ticker_analysis (
    ticker TEXT PRIMARY KEY,
    synthesis TEXT NOT NULL,
    stance TEXT,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS allocation_analysis (
    user_key TEXT PRIMARY KEY,
    output_json TEXT NOT NULL,
    synthesis TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS auth_tokens (
    token TEXT PRIMARY KEY,
    user_key TEXT NOT NULL,
    created_at TEXT NOT NULL
);
"""


def _connect() -> sqlite3.Connection:
    db_path = config.memory_db_path
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.executescript(_SCHEMA)
    return conn


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def get_risk_tolerance(user_key: str) -> str | None:
    with closing(_connect()) as conn:
        row = conn.execute(
            "SELECT value FROM risk_tolerance WHERE user_key = ?", (user_key,)
        ).fetchone()
        return row[0] if row else None


def save_risk_tolerance(user_key: str, value: str) -> None:
    with closing(_connect()) as conn:
        conn.execute(
            """
            INSERT INTO risk_tolerance (user_key, value, updated_at)
            VALUES (?, ?, ?)
            ON CONFLICT(user_key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
            """,
            (user_key, value, _now()),
        )
        conn.commit()


def get_past_analysis(ticker: str) -> dict | None:
    with closing(_connect()) as conn:
        row = conn.execute(
            "SELECT ticker, synthesis, stance, updated_at FROM ticker_analysis WHERE ticker = ?",
            (ticker.upper(),),
        ).fetchone()
        if not row:
            return None
        return {"ticker": row[0], "synthesis": row[1], "stance": row[2], "updated_at": row[3]}


def save_analysis(ticker: str, synthesis: str, stance: str | None = None) -> None:
    with closing(_connect()) as conn:
        conn.execute(
            """
            INSERT INTO ticker_analysis (ticker, synthesis, stance, updated_at)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(ticker) DO UPDATE SET
                synthesis = excluded.synthesis,
                stance = excluded.stance,
                updated_at = excluded.updated_at
            """,
            (ticker.upper(), synthesis, stance, _now()),
        )
        conn.commit()


def get_latest_allocation(user_key: str) -> dict | None:
    with closing(_connect()) as conn:
        row = conn.execute(
            "SELECT output_json, synthesis, updated_at FROM allocation_analysis WHERE user_key = ?",
            (user_key,),
        ).fetchone()
    if not row:
        return None
    return {"output": json.loads(row[0]), "synthesis": row[1], "updated_at": row[2]}


def create_session(user_key: str | None = None) -> tuple[str, str]:
    """Issues a new server-side session credential.

    Generates an unguessable random token (`secrets.token_urlsafe(32)`) and,
    unless `user_key` is supplied (e.g. to reuse an identity across
    devices, not exposed by the API in Milestone 1), a fresh random
    `user_key` (`uuid4`). Returns `(token, user_key)`; the caller (the API
    layer) hands the token back to the client and never accepts a
    client-typed `user_key` again.
    """
    token = secrets.token_urlsafe(32)
    resolved_user_key = user_key or str(uuid.uuid4())
    with closing(_connect()) as conn:
        conn.execute(
            "INSERT INTO auth_tokens (token, user_key, created_at) VALUES (?, ?, ?)",
            (token, resolved_user_key, _now()),
        )
        conn.commit()
    return token, resolved_user_key


def resolve_user_key(token: str) -> str | None:
    """Looks up the `user_key` a session token maps to, or None if the
    token is missing/unknown — callers must reject the request in that
    case rather than falling back to any default identity."""
    if not token:
        return None
    with closing(_connect()) as conn:
        row = conn.execute(
            "SELECT user_key FROM auth_tokens WHERE token = ?", (token,)
        ).fetchone()
        return row[0] if row else None


def save_allocation(user_key: str, output: dict, synthesis: str) -> None:
    with closing(_connect()) as conn:
        conn.execute(
            """INSERT INTO allocation_analysis (user_key, output_json, synthesis, updated_at)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(user_key) DO UPDATE SET output_json = excluded.output_json,
            synthesis = excluded.synthesis, updated_at = excluded.updated_at""",
            (user_key, json.dumps(output), synthesis, _now()),
        )
        conn.commit()
